USE [master]
GO

/****** Object:  Database [demoPRJ301]    Script Date: 8/24/2023 9:51:02 AM ******/
CREATE DATABASE [demoPRJ301]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'demoPRJ301', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\demoPRJ301.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'demoPRJ301_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\demoPRJ301_log.ldf' , SIZE = 73728KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [demoPRJ301].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [demoPRJ301] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [demoPRJ301] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [demoPRJ301] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [demoPRJ301] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [demoPRJ301] SET ARITHABORT OFF 
GO

ALTER DATABASE [demoPRJ301] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [demoPRJ301] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [demoPRJ301] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [demoPRJ301] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [demoPRJ301] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [demoPRJ301] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [demoPRJ301] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [demoPRJ301] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [demoPRJ301] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [demoPRJ301] SET  ENABLE_BROKER 
GO

ALTER DATABASE [demoPRJ301] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [demoPRJ301] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [demoPRJ301] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [demoPRJ301] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [demoPRJ301] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [demoPRJ301] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [demoPRJ301] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [demoPRJ301] SET RECOVERY FULL 
GO

ALTER DATABASE [demoPRJ301] SET  MULTI_USER 
GO

ALTER DATABASE [demoPRJ301] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [demoPRJ301] SET DB_CHAINING OFF 
GO

ALTER DATABASE [demoPRJ301] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [demoPRJ301] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [demoPRJ301] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [demoPRJ301] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [demoPRJ301] SET QUERY_STORE = OFF
GO

ALTER DATABASE [demoPRJ301] SET  READ_WRITE 
GO

